### ISSUE TITLE
Only set ssh key_name if desired by the user

### ISSUE THREAD

**Issue by bhagemeier** [gwdg/rOCCI-cli#29]
When providing an SSH key from the command line, rOCCI-CLI always sets a (hard-coded) name for it accordingly. This does not work in OpenStack, as keys can only be registered once under a name and not be overwritten.

See discussion at https://bugs.launchpad.net/ooi/+bug/1527261/ and particularly comment 4 for further information.

Cheers,
Björn

**Comment by arax** [comment]
Could you, please, reopen this issue on the primary repository [1]?

Yes, this is a valid issue. We are currently setting the `publickey.name` attribute to a static value [2].

[1] https://github.com/EGI-FCTF/rOCCI-cli
[2] https://github.com/EGI-FCTF/rOCCI-cli/blob/master/lib/occi/cli/helpers/create_helper.rb#L116
